/* Shared browser / Node domain rules. No network calls or secrets. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.LocHire=factory()})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const categories=['Domestic help','Cooking','Driving','Cleaning','Plumbing','Electrical work','Painting','Carpentry','Appliance repairs','Gate attendant','Shop assistant'];
const domestic=['Domestic help','Cooking','Cleaning','Gate attendant'];
const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const bases=['Hourly','Daily','Monthly','Per task'];
const uid=()=>typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const norm=s=>String(s||'').trim().toLowerCase();
const list=s=>Array.isArray(s)?s:String(s||'').split(',').map(x=>x.trim()).filter(Boolean);
const clone=x=>JSON.parse(JSON.stringify(x));
function seed(){const date=today();const employers=[
{id:'demo-home',name:'The Adeyemi household',type:'Household',city:'Lagos',area:'Yaba',intro:'A household looking for help with meals and day-to-day home care.',business:'',demo:true},
{id:'demo-cafe',name:'Green Table Kitchen',type:'Business',city:'Lagos',area:'Surulere',intro:'A small neighbourhood kitchen serving weekday lunches.',business:'Neighbourhood food service. Business details are self-reported.',demo:true},
{id:'demo-individual',name:'Nneka O.',type:'Individual',city:'Lagos',area:'Ikeja',intro:'Looking for help with repairs and occasional home maintenance.',demo:true}];
const workerData=[['Amaka Eze','Domestic help','Home cleaning, Laundry','Yaba',90000,'Monthly',3],['Sade Bello','Cooking','Meal preparation, Food hygiene','Surulere',120000,'Monthly',4],['Ibrahim Musa','Driving','Safe driving, Route planning','Ikeja',150000,'Monthly',5],['Funke Ade','Cleaning','Home cleaning, Hygiene','Yaba',15000,'Daily',2],['Chuka Nwosu','Gate attendant','Access control, Visitor records','Yaba',90000,'Monthly',2],['Aisha Ali','Shop assistant','Customer service, Stock keeping','Surulere',100000,'Monthly',2],['Emeka Obi','Plumbing','Leak repairs, Pipe fitting','Ikeja',0,'Per task',6],['Tunde Lawal','Electrical work','Wiring, Fault diagnosis','Yaba',0,'Per task',4],['Bisi Okafor','Painting','Wall preparation, Interior painting','Surulere',25000,'Daily',3],['Daniel Okeke','Carpentry','Furniture repairs, Woodwork','Ikeja',0,'Per task',5],['Ngozi Obi','Appliance repairs','Appliance diagnosis, Repairs','Ikeja',0,'Per task',4]];
const workers=workerData.map((d,i)=>({id:'demo-w'+i,name:d[0],occupation:d[1],speciality:d[2].split(',')[0],skills:list(d[2]),city:'Lagos',area:d[3],years:d[6],experience:d[6]+' years of relevant work (sample).',days:['Mon','Tue','Wed','Thu','Fri'],hoursStart:'08:00',hoursEnd:'17:00',start:date,coverage:[d[3]],travel:true,types:i<6?['Ongoing job','One-off task']:['One-off task'],pay:d[4],basis:d[5],flexible:d[4]===0,accommodation:domestic.includes(d[1])?'Live-out':'Not applicable',workExample:'Fictional example: '+d[2].split(',')[0].toLowerCase()+' for local clients.',references:'Not checked',published:true,demo:true,licence:d[1]==='Driving'?'Self-reported; not checked':''}));
const openingData=[['House help for weekday home care','Domestic help','demo-home','Ongoing job',80000,120000,'Monthly','Home cleaning, Laundry','Support routine home cleaning and laundry.'],['Cook for a neighbourhood kitchen','Cooking','demo-cafe','Ongoing job',100000,160000,'Monthly','Meal preparation, Food hygiene','Prepare weekday lunch meals and maintain kitchen hygiene.'],['Driver for local errands','Driving','demo-home','Ongoing job',130000,180000,'Monthly','Safe driving, Route planning','Drive for agreed local journeys and keep basic vehicle records.'],['Repair a leaking kitchen pipe','Plumbing','demo-individual','One-off task',0,0,'Per task','Leak repairs','Inspect a leaking kitchen pipe and discuss the repair options.'],['Check a faulty electrical socket','Electrical work','demo-home','One-off task',0,0,'Per task','Fault diagnosis','Diagnose a faulty socket and explain the recommended work.'],['Clean a small flat','Cleaning','demo-individual','One-off task',12000,18000,'Per task','Home cleaning','Clean the kitchen, bathroom and living spaces.'],['Gate attendant for daytime shifts','Gate attendant','demo-home','Ongoing job',80000,120000,'Monthly','Access control, Visitor records','Keep visitor records and manage gate entry during agreed daytime shifts.'],['Shop assistant','Shop assistant','demo-cafe','Ongoing job',90000,130000,'Monthly','Customer service, Stock keeping','Help customers, arrange supplies and record stock.'],['Paint one living room','Painting','demo-individual','One-off task',0,0,'Per task','Interior painting','Discuss wall preparation and repainting a living room.'],['Repair a wooden chair','Carpentry','demo-individual','One-off task',0,0,'Per task','Furniture repairs','Inspect a loose wooden chair and propose a safe repair.'],['Diagnose a washing machine','Appliance repairs','demo-individual','One-off task',0,0,'Per task','Appliance diagnosis','Inspect a washing machine that stops mid-cycle.']];
const openings=openingData.map((d,i)=>{const e=employers.find(e=>e.id===d[2]);return{id:'demo-o'+i,title:d[0],category:d[1],employerId:e.id,type:d[3],min:d[4],max:d[5],basis:d[6],skills:list(d[7]),description:d[8],city:e.city,area:e.area,start:date,date:'',duration:d[3]==='One-off task'?'Discuss after inspection':'',days:d[3]==='Ongoing job'?['Mon','Tue','Wed','Thu','Fri']:[],hoursStart:d[3]==='Ongoing job'?'09:00':'',hoursEnd:d[3]==='Ongoing job'?'16:00':'',years:1,quote:d[5]===0,materials:d[3]==='One-off task'?'Discuss together':'Not applicable',accommodation:domestic.includes(d[1])?'Live-out':'Not applicable',status:'Open',photos:[],demo:true}});
return{version:3,workers,employers,openings,engagements:[],reviews:[],blocks:[],worker:null,employer:null};}
function publicProfile(p){if(!p)return null;const {email,phone,address,privateNotes,coordinates,...pub}=p;return clone(pub)}
function participant(g,actor){return actor===g.workerId||actor===g.employerId}
function other(g,actor){if(!participant(g,actor))throw Error('This is not your engagement.');return actor===g.workerId?g.employerId:g.workerId}
function suitability(w,o){const required=list(o.skills);const skills=required.filter(s=>list(w.skills).some(v=>norm(v)===norm(s)));const sameCity=norm(w.city)===norm(o.city);const area=norm(w.area)===norm(o.area)||list(w.coverage).some(a=>norm(a)===norm(o.area));const covered=sameCity&&(area||w.travel===true);const compatible=w.types?.includes(o.type);const rateKnown=!w.flexible&&!o.quote&&w.pay>0&&o.max>0&&w.basis===o.basis;const budget=rateKnown?w.pay<=o.max:null;let schedule=null;
if(o.days?.length&&w.days?.length&&o.hoursStart&&o.hoursEnd&&w.hoursStart&&w.hoursEnd)schedule=o.days.every(d=>w.days.includes(d))&&w.hoursStart<=o.hoursStart&&w.hoursEnd>=o.hoursEnd;
if(o.type==='One-off task'&&o.date&&w.start){let day=days[(new Date(o.date+'T12:00:00').getDay()+6)%7];schedule=w.start<=o.date&&w.days.includes(day)}
if(o.start&&w.start&&w.start>o.start)schedule=false;
return{skills:required.length?`${skills.length} of ${required.length} requested skills listed`:'Required skills not specified',skillFit:skills.length,coverage:covered?'Worker covers this area':sameCity?'Travel to this area needs discussing':'Location coverage needs discussing',budget:budget===null?'Price or payment basis needs discussing':budget?'Expected pay fits the budget':'Expected pay is above the budget',schedule:schedule===null?'Schedule not yet confirmed':schedule?'Listed schedule is compatible':'Schedule needs discussing',budgetFit:budget,scheduleFit:schedule,covered,typeFit:compatible,experience:Number(w.years)>=Number(o.years||0)};}
function validateProfile(p,role){if(!p.name?.trim()||!p.city?.trim()||!p.area?.trim())throw Error('Add a name, city and general area.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email||''))throw Error('Enter a valid private email address.');if(!p.phone?.trim())throw Error('Add a private contact number.');if(role==='worker'){if(!categories.includes(p.occupation)||!p.speciality?.trim())throw Error('Choose an occupation and speciality.');if(!p.types?.length||!p.days?.length)throw Error('Choose work types and working days.');if(!p.hoursStart||!p.hoursEnd||p.hoursEnd<=p.hoursStart)throw Error('Working hours must end after they start.');if(!p.start)throw Error('Choose your earliest start date.');if(!p.flexible&&!(Number(p.pay)>0))throw Error('Add expected pay or choose price depends on the task.');}else{if(!['Individual','Household','Business'].includes(p.type))throw Error('Choose an employer type.');if(!p.intro?.trim())throw Error('Add a short introduction.');if(p.type==='Business'&&!p.business?.trim())throw Error('Add your business details.');}return true;}
function validateOpening(o){if(!categories.includes(o.category)||!['Ongoing job','One-off task'].includes(o.type))throw Error('Choose a category and type of help.');if(!o.title?.trim()||!o.description?.trim()||!o.city?.trim()||!o.area?.trim())throw Error('Complete the title, work description, city and area.');if(!o.quote&&(!(Number(o.max)>0)||Number(o.min)>Number(o.max)))throw Error('Enter a valid budget range.');if(o.type==='One-off task'){if(!o.date||o.date<today()||!o.duration?.trim())throw Error('Add a current or future preferred date and estimated duration.');}else{if(!o.days?.length||!o.hoursStart||o.hoursEnd<=o.hoursStart||!o.start||o.start<today())throw Error('Add working days, valid hours and a current or future start date.');if(!o.skills?.length)throw Error('List at least one required skill.');}return true;}
function createEngagement(o,w,e,initiator,kind){if(o.status!=='Open')throw Error('This opening is closed.');if(initiator!==w.id&&initiator!==e.id)throw Error('Choose your own profile.');return{id:uid(),openingId:o.id,workerId:w.id,employerId:e.id,type:o.type,title:o.title,kind,jobLocation:clone(o.jobLocation||null),status:'Pending',initiator,created:new Date().toISOString(),messages:[],terms:null,version:0,confirmations:{},completion:{},history:[{text:kind+' created locally',at:new Date().toISOString()}]};}
function transition(g,actor,action){if(!participant(g,actor))throw Error('Only a participant can change this record.');if(action==='accept'||action==='decline'){if(g.status!=='Pending'||actor===g.initiator)throw Error('Only the invited party can respond to a pending invitation.');g.status=action==='accept'?'Accepted':'Declined';}
else if(action==='cancel'){if(['Completed','Cancelled','Declined'].includes(g.status))throw Error('This record is already closed.');g.status='Cancelled';}
else if(action==='complete'){if(g.status!=='Confirmed')throw Error('Both parties must confirm the work details first.');g.completion[actor]=true;if(g.completion[g.workerId]&&g.completion[g.employerId])g.status='Completed';}
else throw Error('Unknown action.');g.history.push({text:action+' by '+actor,at:new Date().toISOString()});return g;}
function propose(g,actor,t){if(!participant(g,actor)||!['Accepted','Confirmed'].includes(g.status))throw Error('Accept the conversation before proposing work details.');if(!t.scope?.trim()||!(Number(t.pay)>0)||!bases.includes(t.basis)||!t.schedule?.trim()||!t.start||!t.city?.trim()||!t.area?.trim())throw Error('Complete scope, pay, payment basis, schedule, start date, city and area.');if(g.type==='One-off task'&&(!t.completionDate||t.completionDate<t.start))throw Error('Completion date must be on or after the start date.');g.version+=1;g.terms={...clone(t),pay:Number(t.pay)};g.versions=g.versions||[];g.versions.push({version:g.version,terms:clone(g.terms),proposedBy:actor});g.confirmations={};g.completion={};g.status='Accepted';g.history.push({text:'Work details version '+g.version+' proposed by '+actor,at:new Date().toISOString()});return g;}
function confirm(g,actor,version){if(!participant(g,actor)||g.status!=='Accepted'||!g.terms||version!==g.version)throw Error('Review the current work details before confirming.');g.confirmations[actor]=version;if(g.confirmations[g.workerId]===version&&g.confirmations[g.employerId]===version)g.status='Confirmed';g.history.push({text:'Version '+version+' confirmed by '+actor,at:new Date().toISOString()});return g;}
function addMessage(g,actor,text){if(!participant(g,actor)||['Declined','Cancelled','Completed'].includes(g.status))throw Error('This conversation is closed.');if(!text?.trim())throw Error('Write a message first.');g.messages.push({id:uid(),actor,text:text.trim().slice(0,1500),at:new Date().toISOString()});}
function review(state,g,actor,rating,text){if(g.status!=='Completed'||!participant(g,actor))throw Error('Reviews require a completed engagement and a participant.');if(state.reviews.some(r=>r.engagementId===g.id&&r.author===actor))throw Error('You have already reviewed this engagement.');if(!Number.isInteger(Number(rating))||rating<1||rating>5||!text?.trim())throw Error('Choose 1 to 5 and add a review.');const r={id:uid(),engagementId:g.id,author:actor,target:other(g,actor),rating:Number(rating),text:text.trim().slice(0,1000),at:new Date().toISOString(),demo:true};state.reviews.push(r);return r;}

function eligibleReviews(state,id){return state.reviews.filter(r=>{const g=state.engagements.find(g=>g.id===r.engagementId);return g&&g.status==='Completed'&&participant(g,r.author)&&r.target===id&&other(g,r.author)===id&&Number.isInteger(r.rating)&&r.rating>=1&&r.rating<=5;});}
function ratingSummary(state,id){const reviews=eligibleReviews(state,id);return{count:reviews.length,average:reviews.length?reviews.reduce((s,r)=>s+r.rating,0)/reviews.length:null};}
function validLocation(p){return !!p&&typeof p.lat==='number'&&Number.isFinite(p.lat)&&p.lat>=-90&&p.lat<=90&&typeof p.lon==='number'&&Number.isFinite(p.lon)&&p.lon>=-180&&p.lon<=180&&Number.isFinite(p.accuracy)&&p.accuracy>=0&&Number.isFinite(p.at);}
function distanceMeters(a,b){if(!validLocation(a)||!validLocation(b))return null;const rad=n=>n*Math.PI/180,dlat=rad(b.lat-a.lat),dlon=rad(b.lon-a.lon),h=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlon/2)**2;return 6371000*2*Math.atan2(Math.sqrt(Math.min(1,h)),Math.sqrt(Math.max(0,1-h)));}
function distanceInfo(a,b,now=Date.now()){if(!validLocation(a)||!validLocation(b)||now-a.at>1800000||now-b.at>86400000||a.at>now+60000||b.at>now+60000)return null;const metres=distanceMeters(a,b),uncertainty=a.accuracy+b.accuracy;return{metres,uncertainty,min:Math.max(0,metres-uncertainty),max:metres+uncertainty};}
function withinRadius(info,radius){return !!info&&Number.isFinite(Number(radius))&&Number(radius)>0&&info.min<=Number(radius);}

return{eligibleReviews,ratingSummary,validLocation,distanceMeters,distanceInfo,withinRadius,categories,domestic,days,bases,uid,today,list,norm,clone,seed,publicProfile,suitability,validateProfile,validateOpening,createEngagement,transition,propose,confirm,addMessage,review,participant,other};
});

