const {test}=require('node:test');
const assert=require('node:assert/strict');
const D=require('../domain');
function setup(type='Ongoing job'){const s=D.seed(),o=s.openings.find(o=>o.type===type),w=s.workers.find(w=>w.occupation===o.category),e=s.employers.find(e=>e.id===o.employerId);return {s,o,w,e,g:D.createEngagement(o,w,e,e.id,'Interview invitation')}}
const terms={scope:'Prepare weekday meals',pay:120000,basis:'Monthly',schedule:'Mon to Fri, 9am to 4pm WAT',start:D.today(),city:'Lagos',area:'Yaba',arrangements:'Live-out'};
test('sample data is labelled; no fabricated reviews or contact details',()=>{const s=D.seed();assert.ok(s.workers.every(w=>w.demo&&!w.email&&!w.phone));assert.ok(s.openings.every(o=>o.demo));assert.equal(s.reviews.length,0)});
test('public profile projection removes private contact and address',()=>{const p=D.publicProfile({name:'Ada',email:'private@example.test',phone:'000',address:'private',privateNotes:'private',area:'Yaba'});assert.deepEqual(p,{name:'Ada',area:'Yaba'})});
test('matching separates skills, area, budget and unknown schedule',()=>{const {w,o}=setup();const m=D.suitability(w,o);assert.equal(m.covered,true);assert.equal(m.budgetFit,true);assert.equal(m.scheduleFit,true);assert.match(m.skills,/2 of 2/);const unknown=D.suitability(w,{...o,days:[],hoursStart:'',hoursEnd:'',quote:true});assert.equal(unknown.schedule,'Schedule not yet confirmed');assert.equal(unknown.budgetFit,null);assert.equal(D.suitability(w,{...o,basis:'Daily'}).budgetFit,null);assert.equal(D.suitability(w,{...o,city:'Abuja'}).covered,false)});
test('ongoing journey enforces invited-party response, current-version confirmation and two-sided completion',()=>{const {s,g,w,e}=setup();assert.throws(()=>D.transition(g,e.id,'accept'));assert.throws(()=>D.transition(g,'intruder','accept'));D.transition(g,w.id,'accept');D.propose(g,e.id,terms);assert.throws(()=>D.confirm(g,w.id,0));D.confirm(g,w.id,1);assert.equal(g.status,'Accepted');D.confirm(g,e.id,1);assert.equal(g.status,'Confirmed');D.propose(g,w.id,{...terms,pay:130000});assert.equal(g.version,2);assert.deepEqual(g.confirmations,{});assert.equal(g.versions[0].terms.pay,120000);assert.throws(()=>D.confirm(g,e.id,1));D.confirm(g,w.id,2);D.confirm(g,e.id,2);D.transition(g,w.id,'complete');assert.equal(g.status,'Confirmed');assert.throws(()=>D.review(s,g,w.id,5,'Good'));D.transition(g,e.id,'complete');assert.equal(g.status,'Completed');D.review(s,g,w.id,5,'Clear instructions');D.review(s,g,e.id,4,'Good work');assert.equal(s.reviews.length,2);assert.throws(()=>D.review(s,g,w.id,5,'Duplicate'));assert.throws(()=>D.review(s,g,'intruder',5,'No'));});
test('task scope and quote journey needs agreed positive price and completion date',()=>{const {g,w,e}=setup('One-off task');D.transition(g,w.id,'accept');assert.throws(()=>D.propose(g,e.id,{...terms,pay:0}));assert.throws(()=>D.propose(g,e.id,terms));D.propose(g,w.id,{...terms,scope:'Fix leaking pipe, parts priced separately',pay:12000,basis:'Per task',completionDate:D.today()});D.confirm(g,w.id,1);D.confirm(g,e.id,1);D.transition(g,w.id,'complete');D.transition(g,e.id,'complete');assert.equal(g.status,'Completed')});
test('declined and cancelled records prevent further messages, proposals and confirmations',()=>{for(const action of ['decline','cancel']){const {g,w,e}=setup();D.transition(g,w.id,action);assert.throws(()=>D.addMessage(g,e.id,'Hello'));assert.throws(()=>D.propose(g,e.id,terms));assert.throws(()=>D.confirm(g,e.id,1))}});
test('posting validation distinguishes required task and ongoing fields',()=>{const {o}=setup();assert.equal(D.validateOpening(o),true);assert.throws(()=>D.validateOpening({...o,skills:[]}));const {o:task}=setup('One-off task');assert.throws(()=>D.validateOpening(task));assert.equal(D.validateOpening({...task,date:D.today()}),true);assert.throws(()=>D.validateOpening({...task,date:D.today(),quote:false,min:100,max:50}))});
