const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {DatabaseSync}=require('node:sqlite');
const {JSDOM,VirtualConsole}=require('jsdom');
const root=path.join(__dirname,'..');
const tick=()=>new Promise(resolve=>setTimeout(resolve,25));
async function fixture(extraEnv={}){
  const {handleRequest}=await import('../payment-backend/lib/service.mjs');
  const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');
  for(const f of fs.readdirSync(path.join(root,'payment-backend/drizzle')).filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync(path.join(root,'payment-backend/drizzle',f),'utf8'));
  const db={prepare(sql){return {bind(...values){return {sql,values,first:async()=>sqlite.prepare(sql).get(...values)||null,all:async()=>({results:sqlite.prepare(sql).all(...values)}),run:async()=>({meta:sqlite.prepare(sql).run(...values)})};}};},async batch(statements){sqlite.exec('BEGIN IMMEDIATE');try{const r=statements.map(s=>({meta:sqlite.prepare(s.sql).run(...s.values)}));sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
  const env={DB:db,SERVICE_SECRET:'fixture-service-secret',APP_ORIGIN:'https://lochire.vercel.app',APP_MODE:'production',PAYMENT_MODE:'live',WEMA_MODE:'live',WEMA_ENABLED:'false',WEMA_ENVIRONMENT:'production',...extraEnv};
  let ip=0;const errors=[];
  function browser(options={}){let cookie='';const calls=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:env.APP_ORIGIN,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;
    w.scrollTo=()=>{};w.AbortSignal=global.AbortSignal;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
    w.fetch=async(url,options={})=>{calls.push({path:String(url),body:options.body?JSON.parse(options.body):null});const request=new Request(new URL(url,env.APP_ORIGIN),{method:options.method||'GET',headers:{'x-lochire-service-key':env.SERVICE_SECRET,'x-lochire-client-ip':'fixture-'+(++ip),origin:env.APP_ORIGIN,...(cookie?{cookie}:{}),...options.headers},body:options.body});const response=await handleRequest(request,env);const set=response.headers.get('set-cookie');if(set)cookie=set.split(';')[0];return response;};
    let dark=!!options.dark;const listeners=[];w.matchMedia=()=>({get matches(){return dark;},addEventListener:(event,fn)=>listeners.push(fn)});if(options.theme)w.localStorage.setItem('lochire-theme',options.theme);w.eval(fs.readFileSync(path.join(root,'theme.js'),'utf8'));w.eval(fs.readFileSync(path.join(root,'live-domain.js'),'utf8'));w.eval(fs.readFileSync(path.join(root,'app.js'),'utf8'));
    return {w,calls,deviceTheme(value){dark=value;listeners.forEach(fn=>fn());},close:()=>dom.window.close()};
  }
  return {browser,errors};
}
async function click(b,selector){const el=b.w.document.querySelector(selector);assert.ok(el,selector+' missing');el.click();await tick();}
function fill(b,values){for(const [name,value]of Object.entries(values)){const active=b.w.document.querySelector("dialog[open] form")||b.w.document.querySelector("main form");const el=active?.querySelector(`[name="${name}"]`);assert.ok(el,name+' missing');if(el.type==='checkbox')el.checked=!!value;else el.value=value;el.dispatchEvent(new b.w.Event('change',{bubbles:true}));}}
async function submit(b,id){const f=b.w.document.getElementById(id);assert.ok(f,id+' missing');f.dispatchEvent(new b.w.Event('submit',{bubbles:true,cancelable:true}));for(let i=0;i<160&&f.dataset.submitting==='true';i++)await tick();assert.notEqual(f.dataset.submitting,'true','form submission timed out');await tick();}
async function register(b,label){await click(b,'#account-button');await click(b,'[data-page="account"]');await click(b,'[data-action="auth-login"]');await click(b,'[data-action="auth-register"]');fill(b,{name:label,email:label+'@example.test',phone:'08012345678',password:'SecureFixturePassword123!',termsConsent:true});await submit(b,'auth-form');assert.match(b.w.document.querySelector('main').textContent,/Your work profile/);}
async function switchRole(b,role){await click(b,'#role-button');await click(b,`[data-action="role-${role}"]`);}
async function createProfile(b,worker){await click(b,'[data-action="edit-profile"]');fill(b,worker?{city:'Ibadan',area:'Jericho',occupation:'Plumbing',speciality:'Leak repair',skills:'Pipe fitting',years:'4',experience:'Repair and installation work',pay:'20000',basis:'Per task'}:{city:'Ibadan',area:'Jericho',intro:'A household looking for repairs.'});await submit(b,'profile-form');assert.match(b.w.document.querySelector('main').textContent,/Published/);}

test('the published UI has real account gates, empty discovery and no fictional listings',async()=>{
  const f=await fixture(),b=f.browser();try{await tick();assert.match(b.w.document.querySelector('main').textContent,/Find local workers/);assert.doesNotMatch(b.w.document.body.textContent,/DEMO|Amaka Eze|Green Table Kitchen/);assert.ok(b.w.document.querySelector('[data-action="be-worker"]'));assert.ok(b.w.document.querySelector('[data-action="be-employer"]'));await click(b,'#account-button');assert.match(b.w.document.querySelector('dialog').textContent,/Payments/);await click(b,'[data-action="close"]');await click(b,'[data-action="hire"]');assert.match(b.w.document.querySelector('main').textContent,/0 workers/);await click(b,'[data-action="post"]');assert.equal(b.w.document.querySelector('dialog').open,true);assert.ok(b.w.document.querySelector('#auth-form'));assert.equal(f.errors.length,0);}finally{b.close();}
});

test('two real browser sessions create profiles, post work, agree, complete and publish a review',async()=>{
  const f=await fixture(),w=f.browser(),e=f.browser();try{
    await tick();await register(w,'artisan');await createProfile(w,true);await register(e,'hirer');await switchRole(e,'employer');await createProfile(e,false);
    await click(e,'[data-page="openings"]');await click(e,'[data-action="post"]');const future=new Date(Date.now()+86400000).toISOString().slice(0,10);fill(e,{type:'One-off task',category:'Plumbing',title:'Repair the kitchen pipe',description:'Inspect and repair the leak.',min:'15000',max:'25000',basis:'Per task',skills:'Pipe fitting',date:future,duration:'Two hours',accommodation:'Not applicable'});await submit(e,'opening-form');assert.match(e.w.document.querySelector('main').textContent,/Repair the kitchen pipe/);
    await click(w,'[data-page="discover"]');await click(w,'[data-action="refresh"]');await click(w,'[data-action="view-opening"]');await click(w,'[data-action="apply"]');fill(w,{message:'I can help with this repair.'});await submit(w,'apply-form');await click(w,'[data-action="record"]');assert.match(w.w.document.querySelector('main').textContent,/I can help/);
    await click(e,'[data-page="engagements"]');e.w.dispatchEvent(new e.w.Event('focus'));await tick();await click(e,'[data-action="record"]');await click(e,'[data-op="accept"]');await click(e,'[data-action="terms"]');fill(e,{pay:'20000',scope:'Repair the pipe and check for leaks.',schedule:'10am WAT',start:future,completionDate:future});await submit(e,'terms-form');await click(e,'[data-op="confirm"]');await click(e,'[data-action="eng-final"]');
    w.w.dispatchEvent(new w.w.Event('focus'));await tick();await click(w,'[data-op="confirm"]');await click(w,'[data-action="eng-final"]');assert.match(w.w.document.querySelector('main').textContent,/Confirmed/);
    e.w.dispatchEvent(new e.w.Event('focus'));await tick();await click(e,'#account-button');await click(e,'[data-page="wallet"]');assert.match(e.w.document.querySelector('main').textContent,/Record cash \/ transfer/);await click(e,'[data-action="record-payment"]');fill(e,{amount:'20000',method:'bank_transfer',note:'Kitchen repair transfer'});await submit(e,'payment-form');assert.match(e.w.document.querySelector('main').textContent,/Awaiting worker confirmation/);
    w.w.dispatchEvent(new w.w.Event('focus'));await tick();await click(w,'#account-button');await click(w,'[data-page="wallet"]');assert.match(w.w.document.querySelector('main').textContent,/Awaiting worker confirmation/);await click(w,'[data-action="record"]');await click(w,'[data-action="payment-ack"][data-status="acknowledged"]');await click(w,'#account-button');await click(w,'[data-page="wallet"]');assert.match(w.w.document.querySelector('main').textContent,/Received · worker confirmed/);assert.match(w.w.document.querySelector('.payment-summary').textContent,/₦20,000/);await click(w,'[data-action="record"]');
    e.w.dispatchEvent(new e.w.Event('focus'));await tick();assert.match(e.w.document.querySelector('main').textContent,/Received · worker confirmed/);await click(e,'[data-action="record"]');
    await click(w,'[data-op="complete"]');await click(w,'[data-action="eng-final"]');e.w.dispatchEvent(new e.w.Event('focus'));await tick();await click(e,'[data-op="complete"]');await click(e,'[data-action="eng-final"]');await click(e,'[data-action="review"]');fill(e,{rating:'5',text:'The repair was completed well.'});await submit(e,'review-form');
    await click(e,'[data-action="view-participant"], [data-action="view-person"]');assert.match(e.w.document.querySelector('main').textContent,/5.0 \/ 5/);assert.match(e.w.document.querySelector('main').textContent,/repair was completed well/);assert.equal(f.errors.length,0);
  }finally{w.close();e.close();}
});

test('worker wallet has no funding and role changes preserve the wallet route',async()=>{
  const f=await fixture(),b=f.browser();try{await tick();await register(b,'wallet');await click(b,'#account-button');await click(b,'[data-page="wallet"]');assert.doesNotMatch(b.w.document.querySelector('main').textContent,/Deposit/);assert.match(b.w.document.querySelector('main').textContent,/Online payments are awaiting activation/);assert.equal(b.w.document.querySelector('footer'),null);assert.doesNotMatch(b.w.document.body.textContent,/Wema/);await switchRole(b,'employer');assert.equal(b.w.location.hash,'#wallet');assert.match(b.w.document.querySelector('main').textContent,/Pay a worker/);assert.doesNotMatch(b.w.document.querySelector('main').textContent,/Deposit/);await switchRole(b,'worker');assert.equal(b.w.location.hash,'#wallet');assert.doesNotMatch(b.w.document.querySelector('main').textContent,/Deposit/);assert.equal(f.errors.length,0);}finally{b.close();}
});


test('bank connection checks the name and requires explicit consent and password before saving',async()=>{
 const original=global.fetch;global.fetch=async(url)=>{const path=new URL(url).pathname;return Response.json({status:true,data:path==='/bank'?[{name:'Example Bank',code:'999',currency:'NGN',active:true}]:path==='/bank/resolve'?{account_number:'0123456789',account_name:'ACCOUNT OWNER'}:{subaccount_code:'ACCT_example'}});};
 const f=await fixture({PAYSTACK_ENABLED:'true',PAYSTACK_MODE:'live',PAYSTACK_SECRET_KEY:'sk_live_fixture'}),b=f.browser();try{await tick();await register(b,'bank');await createProfile(b,true);await click(b,'[data-page="wallet"]');await click(b,'[data-action="connect-bank"]');fill(b,{bankCode:'999',accountNumber:'0123456789',consent:true});await submit(b,'bank-resolve-form');assert.match(b.w.document.querySelector('dialog').textContent,/ACCOUNT OWNER/);assert.doesNotMatch(b.w.document.querySelector('dialog').textContent,/0123456789/);fill(b,{password:'WrongPassword123',consent:true});await submit(b,'bank-save-form');assert.match(b.w.document.querySelector('#form-error').textContent,/password/);fill(b,{password:'SecureFixturePassword123!',consent:true});await submit(b,'bank-save-form');assert.match(b.w.document.querySelector('main').textContent,/Example Bank/);assert.match(b.w.document.querySelector('main').textContent,/6789/);assert.doesNotMatch(b.w.document.querySelector('main').textContent,/0123456789/);assert.equal(f.errors.length,0);}finally{b.close();global.fetch=original;}
});

test('appearance follows the device, saves manual choices and survives navigation',async()=>{
 const f=await fixture(),b=f.browser({dark:true});try{await tick();assert.equal(b.w.document.documentElement.dataset.theme,'dark');await click(b,'#account-button');await click(b,'[data-page="settings"]');await click(b,'[data-action="theme-light"]');assert.equal(b.w.document.documentElement.dataset.theme,'light');assert.equal(b.w.localStorage.getItem('lochire-theme'),'light');b.deviceTheme(true);assert.equal(b.w.document.documentElement.dataset.theme,'light');await click(b,'[data-action="theme-dark"]');assert.equal(b.w.document.documentElement.dataset.theme,'dark');await click(b,'[data-page="discover"]');assert.equal(b.w.document.documentElement.dataset.theme,'dark');await click(b,'#account-button');await click(b,'[data-page="settings"]');assert.equal(b.w.document.querySelector('[data-action="theme-dark"]').getAttribute('aria-pressed'),'true');await click(b,'[data-action="theme-system"]');b.deviceTheme(false);assert.equal(b.w.document.documentElement.dataset.theme,'light');assert.equal(b.w.document.querySelector('meta[name="theme-color"]').content,'#f6f8f5');assert.equal(f.errors.length,0);}finally{b.close();}
 const saved=f.browser({theme:'dark'});try{await tick();assert.equal(saved.w.document.documentElement.dataset.theme,'dark');}finally{saved.close();}
});

test('filters expand on demand and preserve their state through refresh',async()=>{
 const f=await fixture(),b=f.browser();try{await tick();assert.equal(b.w.document.querySelector('[data-disclosure="home-more"]').open,false);assert.equal(b.w.document.querySelectorAll('.header-actions button').length,2);assert.equal(b.w.document.querySelectorAll('#nav button').length,4);await click(b,'[data-page="discover"]');assert.equal(b.w.document.querySelector('[data-disclosure="filters"]').open,false);await click(b,'[data-disclosure="filters"] summary');fill(b,{ });const el=b.w.document.querySelector('[name="search-city"]');el.value='Ibadan';el.dispatchEvent(new b.w.Event('input',{bubbles:true}));await click(b,'[data-action="refresh"]');assert.equal(b.w.document.querySelector('[data-disclosure="filters"]').open,true);assert.equal(b.w.document.querySelector('[name="search-city"]').value,'Ibadan');await click(b,'[data-action="clear-filters"]');assert.equal(b.w.document.querySelector('[name="search-city"]').value,'');assert.equal(f.errors.length,0);}finally{b.close();}
});

test('invalid fields in an optional panel reveal themselves before correction',async()=>{
 const f=await fixture(),b=f.browser();try{await tick();await register(b,'hiddenfield');await click(b,'[data-action="edit-profile"]');const details=b.w.document.querySelector('[data-disclosure="availability"]'),input=details.querySelector('[name="hoursStart"]');assert.equal(details.open,false);input.value='';input.dispatchEvent(new b.w.Event('invalid',{cancelable:true}));assert.equal(details.open,true);assert.equal(f.errors.length,0);}finally{b.close();}
});
