import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {handleRequest} from '../lib/service.mjs';
function fixture(){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));
 const db={prepare(sql){return {bind(...values){return {sql,values,first:async()=>sqlite.prepare(sql).get(...values)||null,all:async()=>({results:sqlite.prepare(sql).all(...values)}),run:async()=>({meta:sqlite.prepare(sql).run(...values)})};}};},async batch(statements){sqlite.exec('BEGIN IMMEDIATE');try{const r=statements.map(s=>({meta:sqlite.prepare(s.sql).run(...s.values)}));sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
 const env={DB:db,SERVICE_SECRET:'fixture-service',APP_ORIGIN:'https://lochire.vercel.app',APP_MODE:'production',PAYMENT_MODE:'live',RESEND_API_KEY:'re_fixture_private',EMAIL_FROM:'LocHire <accounts@verified.example>'};let ip=0;
 const call=async(path,body,cookie)=>{const r=await handleRequest(new Request('https://private.example/api/'+path,{method:body===undefined?'GET':'POST',headers:{origin:env.APP_ORIGIN,'x-lochire-service-key':env.SERVICE_SECRET,'x-lochire-client-ip':'fixture-'+(++ip),...(cookie?{cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)}),env);return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 const register=(email='owner@example.test')=>call('auth/register',{name:'Owner',email,phone:'08012345678',role:'both',password:'SecureFixturePassword123!',termsConsent:true});return {db,sqlite,env,call,register};
}
const tokenOf=mail=>mail.text.match(/\/#(?:reset|verify)\/([a-f0-9]{64})/)[1];
async function withMail(fn){const original=global.fetch,mails=[];global.fetch=async(url,opts)=>{assert.equal(url,'https://api.resend.com/emails');mails.push(JSON.parse(opts.body));assert.equal(opts.headers.Authorization,'Bearer re_fixture_private');assert.ok(opts.headers['Idempotency-Key']);return Response.json({id:'email-'+mails.length});};try{await fn(mails);}finally{global.fetch=original;}}
test('signup requests verification and server enforces it before profile or payment mutations',()=>withMail(async mails=>{
 const h=fixture(),r=await h.register();assert.equal(r.status,201);assert.equal(r.data.verificationRequired,true);assert.equal(r.data.verificationEmail.ok,true);assert.equal(mails.length,1);assert.deepEqual(mails[0].to,['owner@example.test']);assert.match(mails[0].text,/https:\/\/lochire.vercel.app\/#verify\//);assert.match(mails[0].html,/Verify email/);const token=tokenOf(mails[0]);assert.notEqual(h.sqlite.prepare('SELECT hash FROM live_email_tokens').get().hash,token);assert.doesNotMatch(JSON.stringify(r.data),new RegExp(token+'|re_fixture_private'));
 assert.equal((await h.call('hiring/profiles/employer',{},r.cookie)).status,403);assert.equal((await h.call('payments/bank/resolve',{},r.cookie)).status,403);
 assert.equal((await h.call('auth/reset',{token,password:'ChangedFixturePassword123!'})).status,400);const v=await h.call('auth/verify',{token});assert.equal(v.status,200);assert.equal(v.data.verifiedUserId,r.data.user.id);assert.equal((await h.call('auth/verify',{token})).status,400);assert.equal((await h.call('hiring/state',undefined,r.cookie)).data.verificationRequired,false);
 const profile=await h.call('hiring/profiles/employer',{name:'Owner',city:'Ibadan',area:'Jericho',type:'Household',intro:'Looking for household help',business:''},r.cookie);assert.equal(profile.status,200);
 const resend=await h.call('auth/verification/request',{},r.cookie);assert.equal(resend.data.alreadyVerified,true);assert.equal(mails.length,1);h.sqlite.close();
}));
test('recovery gives identical answers for existing and unknown accounts and resets once across devices',()=>withMail(async mails=>{
 const h=fixture(),r=await h.register(),second=await h.call('auth/login',{email:'owner@example.test',password:'SecureFixturePassword123!'});const found=await h.call('auth/forgot',{email:'owner@example.test'}),unknown=await h.call('auth/forgot',{email:'missing@example.test'});assert.deepEqual(found.data,unknown.data);assert.equal(found.status,unknown.status);assert.equal(mails.length,2);const token=tokenOf(mails[1]);assert.equal((await h.call('auth/verify',{token})).status,400);
 const concurrent=await Promise.all([h.call('auth/reset',{token,password:'NewSecureFixturePassword123!'}),h.call('auth/reset',{token,password:'AnotherFixturePassword123!'})]);assert.deepEqual(concurrent.map(x=>x.status).sort(),[200,400]);assert.equal((await h.call('hiring/state',undefined,r.cookie)).data.user,null);assert.equal((await h.call('hiring/state',undefined,second.cookie)).data.user,null);assert.equal((await h.call('auth/login',{email:'owner@example.test',password:'SecureFixturePassword123!'})).status,401);assert.equal((await h.call('auth/login',{email:'owner@example.test',password:concurrent[0].status===200?'NewSecureFixturePassword123!':'AnotherFixturePassword123!'})).status,200);h.sqlite.close();
}));
test('expired reset links fail and changing a password invalidates outstanding recovery links',()=>withMail(async mails=>{
 const h=fixture(),r=await h.register();await h.call('auth/forgot',{email:'owner@example.test'});let token=tokenOf(mails[1]);h.sqlite.prepare("UPDATE live_email_tokens SET expires_at=? WHERE purpose='reset'").run(Date.now()-1);assert.equal((await h.call('auth/reset',{token,password:'NewSecureFixturePassword123!'})).status,400);await h.call('auth/forgot',{email:'owner@example.test'});token=tokenOf(mails[2]);assert.equal((await h.call('auth/password',{currentPassword:'WrongSecurePassword123!',password:'NewSecureFixturePassword123!'},r.cookie)).status,401);assert.equal((await h.call('auth/password',{currentPassword:'SecureFixturePassword123!',password:'NewSecureFixturePassword123!'},r.cookie)).status,200);assert.equal((await h.call('auth/reset',{token,password:'AnotherFixturePassword123!'})).status,400);h.sqlite.close();
}));
test('mail failures keep the created account recoverable without leaving usable unmailed tokens',async()=>{
 const original=global.fetch;global.fetch=async()=>{throw Error('Provider unavailable, re_fixture_private');};try{const h=fixture(),r=await h.register();assert.equal(r.status,201);assert.equal(r.data.verificationEmail.ok,false);assert.equal(h.sqlite.prepare('SELECT COUNT(*) n FROM live_email_tokens').get().n,0);assert.doesNotMatch(JSON.stringify(r.data),/re_fixture_private/);assert.equal((await h.call('auth/login',{email:'owner@example.test',password:'SecureFixturePassword123!'})).status,200);const found=await h.call('auth/forgot',{email:'owner@example.test'}),unknown=await h.call('auth/forgot',{email:'missing@example.test'});assert.deepEqual(found.data,unknown.data);h.sqlite.close();}finally{global.fetch=original;}
});

test('test sender emails only its allowed account and keeps recovery answers generic',()=>withMail(async mails=>{
 const h=fixture();h.env.EMAIL_MODE='test';h.env.EMAIL_TEST_RECIPIENT='owner@example.test';
 const owner=await h.register(),other=await h.register('other@example.test');
 assert.equal(owner.data.verificationRequired,true);assert.equal(other.data.verificationRequired,false);assert.equal(other.data.emailReady,false);assert.equal(mails.length,1);
 const found=await h.call('auth/forgot',{email:'owner@example.test'}),blocked=await h.call('auth/forgot',{email:'other@example.test'}),unknown=await h.call('auth/forgot',{email:'missing@example.test'});
 assert.deepEqual(found.data,blocked.data);assert.deepEqual(found.data,unknown.data);assert.equal(mails.length,2);assert.ok(mails.every(m=>m.to[0]==='owner@example.test'));
 const profile=await h.call('hiring/profiles/employer',{name:'Owner',city:'Ibadan',area:'Jericho',type:'Household',intro:'Looking for household help',business:''},other.cookie);assert.equal(profile.status,200);h.sqlite.close();
}));
